version: "2.2"
services:
   scrapyd:
     build: .
     image: scrapyd
     volumes:
       - .:/opt
   nginx:
     build: ./nginx
     ports:
       - "6800:6800"
     links:
       - "scrapyd:scrapyd"
